### ISSUE TITLE
Update to support AutoMapper 11.x

### ISSUE THREAD

**Issue by micdah** [AutoMapper/AutoMapper.Extensions.EnumMapping#11]
Current version is marked as supporting `>= 10.0.0 && < 11.0.0`, so a warning is generated when updating `AutoMapper` to the newly released `11.0.0`.

**Comment by micdah** [comment]
Created PR https://github.com/AutoMapper/AutoMapper.Extensions.EnumMapping/pull/12

**Comment by gabrielmaldi** [comment]
Hi, @micdah, thank you for your work! Now that #12 resolved this issue, will a new version of the package be published to NuGet? Thanks!

**Comment by micdah** [comment]
> Hi, @micdah, thank you for your work! Now that #12 resolved this issue, will a new version of the package be published to NuGet? Thanks!

I think one of the maintainers of the repo will have to trigger a release to have it be published to NuGet. As far as I can see the PR only built an alpha release version which was pushed to a private AutoMapper myGet repository.

**Comment by HenkKin** [comment]
@jbogard, unfortunately something went wrong with the release. An incorrect version (2.0.1-alpha.0.1) of the package was created. I can't find anywhere how to change that version. Please can you help me?

**Comment by jbogard** [comment]
Fixed! The original tag was `v2.0.0.1` which isn't valid SemVer. It needs to be `major.minor.patch`, so I deleted that one and added the `v2.0.1` tag.

**Comment by jbogard** [comment]
I also unlisted the other package with the incorrect version

**Comment by HenkKin** [comment]
Thnx! First release failed due to missing use net6 task in release.yml. So i created a invalid tag in the same release. I thought the release name was used, but it’s the tag name.

 

Thank you very much!

 

Van: Jimmy Bogard ***@***.***> 
Verzonden: vrijdag 7 januari 2022 15:16
Aan: AutoMapper/AutoMapper.Extensions.EnumMapping ***@***.***>
CC: Henk Kin ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [AutoMapper/AutoMapper.Extensions.EnumMapping] Update to support AutoMapper 11.x (Issue #11)

 

Fixed! The original tag was v2.0.0.1 which isn't valid SemVer. It needs to be major.minor.patch, so I deleted that one and added the v2.0.1 tag.

**Comment by HenkKin** [comment]
Thnx!

 

Van: Jimmy Bogard ***@***.***> 
Verzonden: vrijdag 7 januari 2022 15:18
Aan: AutoMapper/AutoMapper.Extensions.EnumMapping ***@***.***>
CC: Henk Kin ***@***.***>; Comment ***@***.***>
Onderwerp: Re: [AutoMapper/AutoMapper.Extensions.EnumMapping] Update to support AutoMapper 11.x (Issue #11)

 

I also unlisted the other package with the incorrect version

**Comment by HenkKin** [comment]
Thanks!

**Comment by gabrielmaldi** [comment]
I just upgraded and everything worked perfectly. Thank you all!
